using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PE44
{
    class Program
    {
        /* Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk  Pj| is minimised; what is the value of D?
         */
        static void Main(string[] args)
        {
            int D = 0;

            // Precalc some pentagonal numbers
            SortedList<int, int> pentagonalNumbers = new SortedList<int, int>();
            SortedList<int, int> pentagonalValues = new SortedList<int, int>(); // For fast lookup, because ContainsValue is slow on pentagonalNumbers sorted list.

            int n = 1;
            int pn = 1;

            do
            {
                pentagonalNumbers.Add(n, pn);
                pentagonalValues.Add(pn, pn);

                n++;

                pn = n * (3 * n - 1) / 2;

            } while (n < 5000);

            // pick pairs
            bool bFound = false;
            for (int jj = 2; jj < pentagonalNumbers.Count; jj++)
            {
                for (int kk = jj - 1; kk > 0; kk--)
                {
                    if (pentagonalValues.ContainsKey(pentagonalNumbers[jj] + pentagonalNumbers[kk]))
                    {
                        if (pentagonalValues.ContainsKey(pentagonalNumbers[jj] - pentagonalNumbers[kk]))
                        {
                            D = Math.Abs( pentagonalNumbers[jj] - pentagonalNumbers[kk]);
                            bFound = true;
                            break;
                        }
                    }

                }

                if( bFound)
                {
                    break;
                }
            }



            Console.WriteLine(D);
            Console.WriteLine("Press any key to continue");
            Console.ReadLine();
        }
    }
}
